{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy.fullname" . }}-config
data:
  squid.conf: |
{{ .Values.config | indent 4}}
  domains.txt: |
{{ .Values.domains | indent 4}}
{{- end -}}
