apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  annotations: {{ .Values.service.annotations | toYaml | nindent 4}}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}